## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "https://radiant-choux-7aba5d.netlify.app/*"
  to = "https://f1n.dev/:splat"
  status = 301
  force = true # COMMENT: ensure that we always redirect
  
[[redirects]]
  from = "https://github.f1n.dev/*"
  to = "https://github.com/Finneasles/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
    
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"